"""empty message

Revision ID: 299915e231d1
Revises: 
Create Date: 2020-01-18 17:06:41.850733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299915e231d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
